# Generated by Django 5.2.6 on 2025-09-16 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('iata_code', models.CharField(blank=True, db_index=True, max_length=3, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'db_table': 'cities',
                'unique_together': {('city', 'country')},
            },
        ),
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_airport', models.CharField(max_length=255)),
                ('destination_airport', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('departure_date_time', models.DateTimeField()),
                ('arrival_date_time', models.DateTimeField()),
                ('flight_duration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_stops', models.PositiveIntegerField(default=0)),
                ('number_of_passengers', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_city', to='api.city')),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_city', to='api.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'flight_bookings',
            },
        ),
        migrations.CreateModel(
            name='ActivityBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('activity_date_time', models.DateTimeField()),
                ('number_of_people', models.PositiveIntegerField(default=1)),
                ('category', models.CharField(max_length=255)),
                ('activity_name', models.CharField(max_length=255)),
                ('activity_url', models.CharField(max_length=255)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_city', to='api.city')),
                ('flight_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_booking', to='api.flightbooking')),
            ],
            options={
                'db_table': 'activity_bookings',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.CharField(blank=True, max_length=500, null=True)),
                ('first_name', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('likes_music', models.BooleanField(default=False)),
                ('likes_sports', models.BooleanField(default=False)),
                ('likes_arts', models.BooleanField(default=False)),
                ('likes_film', models.BooleanField(default=False)),
                ('likes_family', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.city')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
    ]
