# Generated by Django 5.2.6 on 2025-09-10 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic_url', models.URLField(blank=True)),
                ('home_city', models.BigIntegerField(blank=True, help_text='City ID (will be converted to a ForeignKey to City later)', null=True)),
                ('likes_music', models.BooleanField(default=False)),
                ('likes_sports', models.BooleanField(default=False)),
                ('likes_arts', models.BooleanField(default=False)),
                ('likes_film', models.BooleanField(default=False)),
                ('likes_family', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
    ]
