# Generated by Django 5.2.6 on 2025-09-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='iata_code',
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True),
        ),
    ]
