# Generated by Django 5.2.6 on 2025-09-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitybooking',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
