# Generated by Django 5.2.6 on 2025-09-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_activitybooking_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True),
        ),
    ]
