# Generated by Django 5.2.6 on 2025-09-10 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='home_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.city'),
        ),
    ]
