# Generated by Django 5.2.6 on 2025-09-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_city_iata_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='iata_code',
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True, unique=True),
        ),
    ]
