# Generated by Django 5.2.6 on 2025-09-10 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profile_home_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='home_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.city'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic_url',
            field=models.URLField(blank=True, default='https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png'),
        ),
    ]
