# Generated by Django 5.2.6 on 2025-09-10 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_flightbooking'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='flightbooking',
            table='flight_bookings',
        ),
    ]
