# Generated by Django 5.2.6 on 2025-09-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_flightbooking_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightbooking',
            old_name='depature_airport',
            new_name='departure_airport',
        ),
        migrations.RenameField(
            model_name='flightbooking',
            old_name='depature_date_time',
            new_name='departure_date_time',
        ),
    ]
