# Generated by Django 5.2.6 on 2025-09-10 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_depature_airport_flightbooking_departure_airport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightbooking',
            name='departure_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_city', to='api.city'),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='destination_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_city', to='api.city'),
        ),
        migrations.CreateModel(
            name='ActivityBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('activity_date_time', models.DateTimeField()),
                ('number_of_people', models.PositiveIntegerField(default=1)),
                ('category', models.CharField(max_length=255)),
                ('activity_name', models.CharField(max_length=255)),
                ('activity_url', models.CharField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flight_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_booking', to='api.flightbooking')),
                ('location_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_city', to='api.city')),
            ],
            options={
                'db_table': 'activity_bookings',
            },
        ),
    ]
