# Generated by Django 5.2.6 on 2025-09-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_flightbooking_departure_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitybooking',
            name='activity_url',
            field=models.CharField(max_length=255),
        ),
    ]
