# Generated by Django 5.2.6 on 2025-09-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_activitybooking_activity_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/Portrait_Placeholder.png', upload_to='profile_pics/'),
        ),
    ]
