# Generated by Django 5.2.6 on 2025-09-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_profile_profile_pic_url_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='iata_code',
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True, unique=True),
        ),
    ]
