branch-defaults:
  default:
    environment: voyagera-api-env
    group_suffix: null
global:
  application_name: backend
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.11
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: voyagera
  repository: null
  sc: null
  workspace_type: Application
